# Form implementation generated from reading ui file 'page_ver3.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
#
##                       _oo0oo_
##                      o8888888o
##                      88" . "88
##                      (| ^_^ |)
##                      0\  =  /0
##                    ___/`---'\___
##                  .' \\|     |// '.
##                 / \\|||  :  |||// \
##                / _||||| -:- |||||- \
##               |   | \\\  -  /// |   |
##               | \_|  ''\---/''  |_/ |
##               \  .-\__  '-'  ___/-. /
##             ___'. .'  /--.--\  `. .'___
##          ."" '<  `.___\_<|>_/___.' >' "".
##         | | :  `- \`.;`\ _ /`;.`/ - ` : | |
##         \  \ `_.   \_ __\ /__ _/   .-` /  /
##     =====`-.____`.___ \_____/___.-`___.-'=====
##                       `=---='
##
##     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##       Phat phu ho, qua môn và không bao gio BUG 
##  Buddha bless me to pass Robot In Practice and never BUG
##     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

from PyQt6 import QtCore, QtGui, QtWidgets
import kinematicRobot



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1139, 665)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color :rgb(85, 170, 255)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(210, 10, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 210, 731, 271))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(80, 30, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:rgb(255, 170, 127)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:rgb(255, 170, 127)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:rgb(224, 98, 255)")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:rgb(255, 61, 135)")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 190, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color:rgb(85, 170, 0)")
        self.label_6.setObjectName("label_6")
        self.x1 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.x1.setGeometry(QtCore.QRect(80, 70, 91, 20))
        self.x1.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.x1.setObjectName("x1")
        self.y1 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.y1.setGeometry(QtCore.QRect(80, 110, 91, 20))
        self.y1.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.y1.setObjectName("y1")
        self.z1 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.z1.setGeometry(QtCore.QRect(80, 150, 91, 20))
        self.z1.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.z1.setObjectName("z1")
        self.send = QtWidgets.QPushButton(parent=self.groupBox)
        self.send.setGeometry(QtCore.QRect(340, 230, 101, 31))
        self.send.setStyleSheet("background-color:rgb(255, 107, 48)")
        self.send.setObjectName("send")
        self.x2 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.x2.setGeometry(QtCore.QRect(220, 70, 91, 20))
        self.x2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.x2.setObjectName("x2")
        self.x3 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.x3.setGeometry(QtCore.QRect(350, 70, 91, 20))
        self.x3.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.x3.setObjectName("x3")
        self.x4 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.x4.setGeometry(QtCore.QRect(470, 70, 91, 20))
        self.x4.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.x4.setObjectName("x4")
        self.x5 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.x5.setGeometry(QtCore.QRect(590, 70, 91, 20))
        self.x5.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.x5.setObjectName("x5")
        self.y2 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.y2.setGeometry(QtCore.QRect(220, 110, 91, 20))
        self.y2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.y2.setObjectName("y2")
        self.y3 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.y3.setGeometry(QtCore.QRect(350, 110, 91, 20))
        self.y3.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.y3.setObjectName("y3")
        self.y4 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.y4.setGeometry(QtCore.QRect(470, 110, 91, 20))
        self.y4.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.y4.setObjectName("y4")
        self.y5 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.y5.setGeometry(QtCore.QRect(590, 110, 91, 20))
        self.y5.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.y5.setObjectName("y5")
        self.z2 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.z2.setGeometry(QtCore.QRect(220, 150, 91, 20))
        self.z2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.z2.setObjectName("z2")
        self.z3 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.z3.setGeometry(QtCore.QRect(350, 150, 91, 20))
        self.z3.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.z3.setObjectName("z3")
        self.z4 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.z4.setGeometry(QtCore.QRect(470, 150, 91, 20))
        self.z4.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.z4.setObjectName("z4")
        self.z5 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.z5.setGeometry(QtCore.QRect(590, 150, 91, 20))
        self.z5.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.z5.setObjectName("z5")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(210, 30, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color:rgb(255, 170, 127)")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(350, 30, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color:rgb(255, 170, 127)")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(470, 30, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color:rgb(255, 170, 127)")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(590, 30, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color:rgb(255, 170, 127)")
        self.label_11.setObjectName("label_11")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(180, 60, 181, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.connect = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.connect.setGeometry(QtCore.QRect(50, 62, 75, 31))
        self.connect.setStyleSheet("background-color:rgb(255, 170, 127)")
        self.connect.setObjectName("connect")
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.label.setStyleSheet("background-color:rgb(255, 170, 0)")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(70, 20, 60, 22))
        self.comboBox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("baud1",115200)
        self.comboBox.addItem("baud2",9600)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 490, 131, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.reset = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.reset.setGeometry(QtCore.QRect(10, 20, 111, 51))
        self.reset.setStyleSheet("background-color:rgb(255, 213, 58)")
        self.reset.setObjectName("reset")
        self.auto_2 = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.auto_2.setGeometry(QtCore.QRect(10, 80, 111, 51))
        self.auto_2.setStyleSheet("background-color:rgb(255, 123, 15)")
        self.auto_2.setObjectName("auto_2")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(420, 60, 181, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(50, 20, 91, 16))
        self.label_12.setStyleSheet("background-color:rgb(255, 170, 0)")
        self.label_12.setObjectName("label_12")
        self.connectwifi = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.connectwifi.setGeometry(QtCore.QRect(50, 60, 91, 31))
        self.connectwifi.setStyleSheet("background-color:rgb(255, 85, 127)")
        self.connectwifi.setObjectName("connectwifi")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(230, 490, 231, 131))
        self.groupBox_5.setObjectName("groupBox_5")
        self.auto_iot = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.auto_iot.setGeometry(QtCore.QRect(10, 50, 91, 41))
        self.auto_iot.setStyleSheet("background-color:rgb(255, 170, 127)")
        self.auto_iot.setObjectName("auto_iot")
        self.mqtt = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.mqtt.setGeometry(QtCore.QRect(130, 50, 91, 41))
        self.mqtt.setStyleSheet("background-color:rgb(255, 170, 255)")
        self.mqtt.setObjectName("mqtt")
        self.home = QtWidgets.QPushButton(parent=self.centralwidget)
        self.home.setGeometry(QtCore.QRect(564, 530, 131, 61))
        self.home.setStyleSheet("background-color:rgb(255, 255, 0)")
        self.home.setObjectName("home")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(60, 80, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color:rgb(255, 170, 0)")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 110, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color:rgb(85, 170, 0)")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 140, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color:rgb(255, 255, 127)")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(690, 90, 47, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color:rgb(255, 255, 127)")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(660, 120, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.label_17.setObjectName("label_17")
        MainWindow.setCentralWidget(self.centralwidget)
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(770, 10, 361, 231))
        self.groupBox_6.setStyleSheet("background-color:rgb(255, 212, 181)")
        self.groupBox_6.setObjectName("groupBox_6")
        self.forwardtinh = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.forwardtinh.setGeometry(QtCore.QRect(140, 120, 75, 23))
        self.forwardtinh.setStyleSheet("background-color:rgb(85, 170, 127)")
        self.forwardtinh.setObjectName("forwardtinh")
        self.run_fk = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.run_fk.setGeometry(QtCore.QRect(140, 50, 75, 23))
        self.run_fk.setStyleSheet("background-color:rgb(85, 170, 127)")
        self.run_fk.setObjectName("run_fk")
        self.xoa_fk = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.xoa_fk.setGeometry(QtCore.QRect(140, 185, 75, 23))
        self.xoa_fk.setStyleSheet("background-color:rgb(85, 170, 127)")
        self.xoa_fk.setObjectName("xoa_fk")
        self.label_18 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_18.setGeometry(QtCore.QRect(20, 30, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color:rgb(255, 170, 0);\n"
"")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_19.setGeometry(QtCore.QRect(20, 90, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color:rgb(255, 85, 0)")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(20, 160, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color:rgb(170, 85, 255)")
        self.label_20.setObjectName("label_20")
        self.theta1 = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.theta1.setGeometry(QtCore.QRect(10, 50, 91, 31))
        self.theta1.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.theta1.setObjectName("theta1")
        self.theta2 = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.theta2.setGeometry(QtCore.QRect(10, 120, 91, 31))
        self.theta2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.theta2.setObjectName("theta2")
        self.theta3 = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.theta3.setGeometry(QtCore.QRect(10, 180, 91, 31))
        self.theta3.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.theta3.setObjectName("theta3")
        self.label_21 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(300, 30, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color:rgb(255, 170, 0)")
        self.label_21.setObjectName("label_21")
        self.xvalue = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.xvalue.setGeometry(QtCore.QRect(260, 50, 91, 31))
        self.xvalue.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.xvalue.setObjectName("xvalue")
        self.label_22 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_22.setGeometry(QtCore.QRect(300, 90, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color:rgb(255, 85, 0)")
        self.label_22.setObjectName("label_22")
        self.yvalue = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.yvalue.setGeometry(QtCore.QRect(260, 120, 91, 31))
        self.yvalue.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.yvalue.setObjectName("yvalue")
        self.label_23 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(300, 160, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color:rgb(170, 85, 255)")
        self.label_23.setObjectName("label_23")
        self.zvalue = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.zvalue.setGeometry(QtCore.QRect(260, 180, 91, 31))
        self.zvalue.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.zvalue.setObjectName("zvalue")
        self.groupBox_7 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(770, 280, 361, 251))
        self.groupBox_7.setStyleSheet("background-color:rgb(226, 226, 169)")
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_35 = QtWidgets.QLabel(parent=self.groupBox_7)
        self.label_35.setGeometry(QtCore.QRect(280, 30, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("background-color:rgb(255, 170, 0);\n"
"")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(parent=self.groupBox_7)
        self.label_36.setGeometry(QtCore.QRect(40, 30, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("background-color:rgb(255, 170, 0)")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(parent=self.groupBox_7)
        self.label_37.setGeometry(QtCore.QRect(280, 100, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("background-color:rgb(255, 85, 0)")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(parent=self.groupBox_7)
        self.label_38.setGeometry(QtCore.QRect(40, 100, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("background-color:rgb(255, 85, 0)")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(parent=self.groupBox_7)
        self.label_39.setGeometry(QtCore.QRect(40, 160, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("background-color:rgb(170, 85, 255)")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(parent=self.groupBox_7)
        self.label_40.setGeometry(QtCore.QRect(280, 170, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("background-color:rgb(170, 85, 255)")
        self.label_40.setObjectName("label_40")
        self.inverttheta1 = QtWidgets.QLineEdit(parent=self.groupBox_7)
        self.inverttheta1.setGeometry(QtCore.QRect(260, 60, 91, 31))
        self.inverttheta1.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.inverttheta1.setObjectName("inverttheta1")
        self.inverttheta2 = QtWidgets.QLineEdit(parent=self.groupBox_7)
        self.inverttheta2.setGeometry(QtCore.QRect(260, 120, 91, 31))
        self.inverttheta2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.inverttheta2.setObjectName("inverttheta2")
        self.inverttheta3 = QtWidgets.QLineEdit(parent=self.groupBox_7)
        self.inverttheta3.setGeometry(QtCore.QRect(260, 190, 91, 31))
        self.inverttheta3.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.inverttheta3.setObjectName("inverttheta3")
        self.invertx = QtWidgets.QLineEdit(parent=self.groupBox_7)
        self.invertx.setGeometry(QtCore.QRect(10, 50, 91, 31))
        self.invertx.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.invertx.setObjectName("invertx")
        self.inverty = QtWidgets.QLineEdit(parent=self.groupBox_7)
        self.inverty.setGeometry(QtCore.QRect(10, 120, 91, 31))
        self.inverty.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.inverty.setObjectName("inverty")
        self.invertz = QtWidgets.QLineEdit(parent=self.groupBox_7)
        self.invertz.setGeometry(QtCore.QRect(10, 190, 91, 31))
        self.invertz.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.invertz.setObjectName("invertz")
        self.inverttinh = QtWidgets.QPushButton(parent=self.groupBox_7)
        self.inverttinh.setGeometry(QtCore.QRect(150, 120, 75, 23))
        self.inverttinh.setStyleSheet("background-color:rgb(170, 170, 255)")
        self.inverttinh.setObjectName("inverttinh")
        self.run_ik = QtWidgets.QPushButton(parent=self.groupBox_7)
        self.run_ik.setGeometry(QtCore.QRect(150, 50, 75, 23))
        self.run_ik.setStyleSheet("background-color:rgb(170, 170, 255)")
        self.run_ik.setObjectName("run_ik")
        self.xoa_ik = QtWidgets.QPushButton(parent=self.groupBox_7)
        self.xoa_ik.setGeometry(QtCore.QRect(150, 190, 75, 23))
        self.xoa_ik.setStyleSheet("background-color:rgb(170, 170, 255)")
        self.xoa_ik.setObjectName("xoa_ik")
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 22))
        self.menubar.setObjectName("menubar")
        self.slidertheta1 = QtWidgets.QSlider(parent=self.centralwidget)
        self.slidertheta1.setGeometry(QtCore.QRect(890, 540, 160, 16))
        self.slidertheta1.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slidertheta1.setObjectName("slidertheta1")
        self.slidertheta2 = QtWidgets.QSlider(parent=self.centralwidget)
        self.slidertheta2.setGeometry(QtCore.QRect(890, 580, 160, 16))
        self.slidertheta2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slidertheta2.setObjectName("slidertheta2")
        self.slidertheta3 = QtWidgets.QSlider(parent=self.centralwidget)
        self.slidertheta3.setGeometry(QtCore.QRect(890, 620, 160, 16))
        self.slidertheta3.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slidertheta3.setObjectName("slidertheta3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
        self.slidertheta1.setMinimum(-90)
        self.slidertheta1.setMaximum(90)
        self.slidertheta1.setValue(0)
        self.slidertheta1.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.slidertheta1.setTickInterval(4)
        
        self.slidertheta2.setMinimum(-90)
        self.slidertheta2.setMaximum(90)
        self.slidertheta2.setValue(0)
        self.slidertheta2.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.slidertheta2.setTickInterval(4)


        self.slidertheta3.setMinimum(-30)
        self.slidertheta3.setMaximum(30)
        self.slidertheta3.setValue(0)
        self.slidertheta3.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.slidertheta3.setTickInterval(4)
        
        self.connect.clicked.connect(self.connect_uart)
        self.connectwifi.clicked.connect(self.connect_wifi) 
        self.send.clicked.connect(self.send_data)
        self.auto_2.clicked.connect(self.run_auto)
        self.reset.clicked.connect(self.reset_pos)
        self.home.clicked.connect(self.set_home)
        self.forwardtinh.clicked.connect(self.fk_compute)
        self.inverttinh.clicked.connect(self.ik_compute)
        self.xoa_fk.clicked.connect(self.delete_fk_value)
        self.xoa_ik.clicked.connect(self.delete_ik_value)
        self.run_fk.clicked.connect(self.run_forward)
        self.run_ik.clicked.connect(self.run_invert)
        self.slidertheta1.valueChanged.connect(self.update_label1)
        self.slidertheta2.valueChanged.connect(self.update_lable2)
        self.slidertheta3.valueChanged.connect(self.update_lable3)
        
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "GIAO DIỆN ĐIỀU KHIỂN ROBOT"))
        self.groupBox.setTitle(_translate("MainWindow", "Set vị trị 5 điểm"))
        self.label_2.setText(_translate("MainWindow", " Position 1"))
        self.label_3.setText(_translate("MainWindow", "  Px"))
        self.label_4.setText(_translate("MainWindow", "  Py"))
        self.label_5.setText(_translate("MainWindow", "  Pz"))
        self.label_6.setText(_translate("MainWindow", "Time"))
        self.x1.setPlaceholderText(_translate("MainWindow", "          X1"))
        self.y1.setPlaceholderText(_translate("MainWindow", "          Y1"))
        self.z1.setPlaceholderText(_translate("MainWindow", "          Z1"))
        self.send.setText(_translate("MainWindow", "Send"))
        self.x2.setPlaceholderText(_translate("MainWindow", "          X2"))
        self.x3.setPlaceholderText(_translate("MainWindow", "          X3"))
        self.x4.setPlaceholderText(_translate("MainWindow", "          X4"))
        self.x5.setPlaceholderText(_translate("MainWindow", "          X5"))
        self.y2.setPlaceholderText(_translate("MainWindow", "          Y2"))
        self.y3.setPlaceholderText(_translate("MainWindow", "          Y3"))
        self.y4.setPlaceholderText(_translate("MainWindow", "          Y4"))
        self.y5.setPlaceholderText(_translate("MainWindow", "          Y5"))
        self.z2.setPlaceholderText(_translate("MainWindow", "          Z2"))
        self.z3.setPlaceholderText(_translate("MainWindow", "          Z3"))
        self.z4.setPlaceholderText(_translate("MainWindow", "          Z4"))
        self.z5.setPlaceholderText(_translate("MainWindow", "          Z5"))
        self.label_8.setText(_translate("MainWindow", " Position 2"))
        self.label_9.setText(_translate("MainWindow", " Position 3"))
        self.label_10.setText(_translate("MainWindow", " Position 4"))
        self.label_11.setText(_translate("MainWindow", " Position 5"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Connection"))
        self.connect.setText(_translate("MainWindow", "Connect"))
        self.label.setText(_translate("MainWindow", "BaudRate"))
        self.comboBox.setItemText(0, _translate("MainWindow", "115200"))
        self.comboBox.setItemText(1, _translate("MainWindow", "9600"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Auto"))
        self.reset.setText(_translate("MainWindow", "Reset Position"))
        self.auto_2.setText(_translate("MainWindow", "RUN_AUTO"))
        self.groupBox_4.setTitle(_translate("MainWindow", "WIFI"))
        self.label_12.setText(_translate("MainWindow", "CONNECT WIFI"))
        self.connectwifi.setText(_translate("MainWindow", "CONNECT WIFI"))
        self.groupBox_5.setTitle(_translate("MainWindow", "IOT_EXPAND"))
        self.auto_iot.setText(_translate("MainWindow", "RUN AUTO IOT"))
        self.mqtt.setText(_translate("MainWindow", "WEBSERVER"))
        self.home.setText(_translate("MainWindow", "HOME"))
        self.label_13.setText(_translate("MainWindow", "SVTH"))
        self.label_14.setText(_translate("MainWindow", "Nguyễn Trọng Tín 21151174"))
        self.label_15.setText(_translate("MainWindow", "Nguyễn Tài Tuệ 21151490"))
        self.label_16.setText(_translate("MainWindow", "GVHD"))
        self.label_17.setText(_translate("MainWindow", "TS Đặng Xuân Ba"))
        self.groupBox_6.setTitle(_translate("MainWindow", "FORWARD KINEMATIC"))
        self.forwardtinh.setText(_translate("MainWindow", "Convert"))
        self.run_fk.setText(_translate("MainWindow", "Run FK"))
        self.xoa_fk.setText(_translate("MainWindow", "Delete"))
        self.label_18.setText(_translate("MainWindow", "Theta1"))
        self.label_19.setText(_translate("MainWindow", "Theta2"))
        self.label_20.setText(_translate("MainWindow", "Theta3"))
        self.label_21.setText(_translate("MainWindow", "X"))
        self.label_22.setText(_translate("MainWindow", "Y"))
        self.label_23.setText(_translate("MainWindow", "Z"))
        self.groupBox_7.setTitle(_translate("MainWindow", "INVERT KINEMATIC"))
        self.label_35.setText(_translate("MainWindow", "Theta1"))
        self.label_36.setText(_translate("MainWindow", "X"))
        self.label_37.setText(_translate("MainWindow", "Theta2"))
        self.label_38.setText(_translate("MainWindow", "Y"))
        self.label_39.setText(_translate("MainWindow", "Z"))
        self.label_40.setText(_translate("MainWindow", "Theta3"))
        self.inverttinh.setText(_translate("MainWindow", "Convert"))
        self.run_ik.setText(_translate("MainWindow", "RUN IK"))
        self.xoa_ik.setText(_translate("MainWindow", "Delete IK"))

        

    def __init__(self):
        self.serial = None  # Đối tượng UART dùng chung


    def connect_uart(self):
        # Kiểm tra nếu đã kết nối
        if self.serial is None or not self.serial.is_open:
            select_data = self.comboBox.currentData()
            if select_data is not None:
                try:
                    self.serial = serial.Serial(port="COM4", baudrate=select_data)
                    time.sleep(2)  # Đợi kết nối ổn định
                    data_to_send = {"type": "command", "command": "CONNECT"}
                    json_data = json.dumps(data_to_send) + "\n"
                    self.serial.write(json_data.encode('utf-8'))

                    response = self.serial.readline().decode().strip()
                    if response == "ESP32 Connected":
                        QtWidgets.QMessageBox.information(None, "Kết Nối", "Kết Nối Thành Công")
                    else:
                        QtWidgets.QMessageBox.warning(None, "Kết Nối", "Kết Nối Thất Bại")
                except serial.SerialException as e:
                    QtWidgets.QMessageBox.critical(None, "Lỗi", f"Lỗi UART: {str(e)}")
        else:
            QtWidgets.QMessageBox.information(None, "Kết Nối", "UART đã được kết nối")

    def send_command(self, command_type, command):
        if self.serial and self.serial.is_open:
            data_to_send = {"type": command_type, "command": command}
            json_data = json.dumps(data_to_send) + "\n"
            self.serial.write(json_data.encode('utf-8'))
            response = self.serial.readline().decode().strip()
            return response
        else:
            QtWidgets.QMessageBox.warning(None, "Lỗi", "UART chưa được kết nối!")

    def connect_wifi(self):
        response = self.send_command("command", "WIFI")
        if response == "Connected to WiFi":
            QtWidgets.QMessageBox.information(None, "Kết Nối WIFI", "Kết Nối WIFI Thành Công")
        else:
            QtWidgets.QMessageBox.warning(None, "Kết Nối WIFI", "Kết Nối WIFI Thất Bại")

    def send_data(self):
        if self.serial and self.serial.is_open:
            ## vi tri dau tien
            X1 = int(float(self.x1.text()))
            Y1 = int(float(self.y1.text()))
            Z1 = int(float(self.z1.text()))
            
            ## vi tri thu 2
            X2 = int(float(self.x2.text()))
            Y2 = int(float(self.y2.text()))
            Z2 = int(float(self.z2.text()))
            
            # vi tri thu 3
            X3 = int(float(self.x3.text()))
            Y3 = int(float(self.y3.text()))
            Z3 = int(float(self.z3.text()))

            # vi tri thu 4
            X4 = int(float(self.x4.text()))
            Y4 = int(float(self.y4.text()))
            Z4 = int(float(self.z4.text()))
            
            #vi tri thu 5
            X5 = int(float(self.x5.text()))
            Y5 = int(float(self.y5.text()))
            Z5 = int(float(self.z5.text()))
            
            t1_1 = kinematicRobot.Inverse_Kinematic(X1,Y1,Z1)[0]
            t2_1 = kinematicRobot.Inverse_Kinematic(X1,Y1,Z1)[1]
            t3_1 = kinematicRobot.Inverse_Kinematic(X1,Y1,Z1)[2]

            t1_2 = kinematicRobot.Inverse_Kinematic(X2,Y2,Z2)[0]
            t2_2 = kinematicRobot.Inverse_Kinematic(X2,Y2,Z2)[1]
            t3_2 = kinematicRobot.Inverse_Kinematic(X2,Y2,Z2)[2]
            
            t1_3 = kinematicRobot.Inverse_Kinematic(X3,Y3,Z3)[0]
            t2_3 = kinematicRobot.Inverse_Kinematic(X3,Y3,Z3)[1]
            t3_3 = kinematicRobot.Inverse_Kinematic(X3,Y3,Z3)[2]
            
            t1_4 = kinematicRobot.Inverse_Kinematic(X4,Y4,Z4)[0]
            t2_4 = kinematicRobot.Inverse_Kinematic(X4,Y4,Z4)[1]
            t3_4 = kinematicRobot.Inverse_Kinematic(X4,Y4,Z4)[2]
            
            t1_5 = kinematicRobot.Inverse_Kinematic(X5,Y5,Z5)[0]
            t2_5 = kinematicRobot.Inverse_Kinematic(X5,Y5,Z5)[1]
            t3_5 = kinematicRobot.Inverse_Kinematic(X5,Y5,Z5)[2]
            
            data_to_send = {
                "type": "position",
                "x1": int(t1_1), "y1": int(t2_1), "z1": int(t3_1),
                "x2": int(t1_2), "y2": int(t2_2), "z2": int(t3_2),
                "x3": int(t1_3), "y3": int(t2_3), "z3": int(t3_3),
                "x4": int(t1_4), "y4": int(t2_4), "z4": int(t3_4),
                "x5": int(t1_5), "y5": int(t2_5), "z5": int(t3_5),
            }
            json_data = json.dumps(data_to_send) + "\n"
            self.serial.write(json_data.encode('utf-8'))
            self.serial.timeout = 2
            response = self.serial.readline().decode().strip()
            if response == "done save pos":
                QtWidgets.QMessageBox.information(None, "Lưu Lệnh", "Đã lưu lệnh")
            else:
                QtWidgets.QMessageBox.warning(None, "Timeout", "Không nhận được phản hồi từ ESP32")

    def run_auto(self):
        self.send_command("command", "autorun")

    def reset_pos(self):
        response = self.send_command("command", "delete")
        if response == "None data in Robot":
            QtWidgets.QMessageBox.information(None, "Reset", "Robot chưa có lệnh học!")
        else:
            QtWidgets.QMessageBox.information(None, "Reset", "Đã xóa lệnh!")

    def set_home(self):
        response = self.send_command("command", "sethome")
        if response == "home":
            QtWidgets.QMessageBox.information(None, "Set Home", "Set home thành công!")
        else:
            QtWidgets.QMessageBox.warning(None, "Set Home", "Set home thất bại!") 
    
    def run_forward(self):
        if self.serial and self.serial.is_open:
            data_to_send = {
                "type":"FK",
                "theta1": int(float(self.theta1.text())),
                "theta2": int(float(self.theta2.text())),
                "theta3": int(float(self.theta3.text()))
            }
        json_data = json.dumps(data_to_send) + "\n"
        self.serial.write(json_data.encode('utf-8'))
        response = self.serial.readline().decode().strip()
        if response == "done fk":
            QtWidgets.QMessageBox.information(None, "Xong", "Đã Chạy Xong FK")
            
    def run_invert(self):
        if self.serial and self.serial.is_open:
            data_to_send = {
                "type":"IK",
                "theta1_ik": int(float(self.inverttheta1.text())),
                "theta2_ik": int(float(self.inverttheta2.text())),
                "theta3_ik": int(float(self.inverttheta3.text()))
            }
        json_data = json.dumps(data_to_send) + "\n"
        self.serial.write(json_data.encode('utf-8'))
        response = self.serial.readline().decode().strip()
        if response == "done ik":
            QtWidgets.QMessageBox.information(None, "Xong", "Đã Chạy Xong IK")

    def fk_compute(self):
        t1 = float(self.theta1.text())
        t2 = float(self.theta2.text())
        t3 = float(self.theta3.text())
        x = kinematicRobot.Forward_Kinematic(t1,t2,t3)[0]
        y = kinematicRobot.Forward_Kinematic(t1,t2,t3)[1]
        z = kinematicRobot.Forward_Kinematic(t1,t2,t3)[2]        
        self.xvalue.setText(str(x))
        self.yvalue.setText(str(y)) 
        self.zvalue.setText(str(z))
        
    def ik_compute(self):
        x1 = float(self.invertx.text())
        y1 = float(self.inverty.text())
        z1 = float(self.invertz.text())
        the1 = kinematicRobot.Inverse_Kinematic(x1,y1,z1)[0]
        the2 = kinematicRobot.Inverse_Kinematic(x1,y1,z1)[1]
        the3 = kinematicRobot.Inverse_Kinematic(x1,y1,z1)[2]
        self.inverttheta1.setText(str(the1))
        self.inverttheta2.setText(str(the2))
        self.inverttheta3.setText(str(the3))
        
    def delete_fk_value(self):
        self.theta1.setText(" ")
        self.theta2.setText(" ")
        self.theta3.setText(" ")
        self.xvalue.setText(" ")
        self.yvalue.setText(" ")
        self.zvalue.setText(" ")
        
    def delete_ik_value(self):
        self.inverttheta1.setText(" ")
        self.inverttheta2.setText(" ")
        self.inverttheta3.setText(" ")
        self.invertx.setText(" ")
        self.inverty.setText(" ")
        self.invertz.setText(" ")
        
    def update_label1(self):
        self.theta1.setText(str(self.slidertheta1.value()))

    
    def update_lable2(self):
        self.theta2.setText(str(self.slidertheta2.value()))
    
    def update_lable3(self):
        self.theta3.setText(str(self.slidertheta3.value()))

        
        
    # def connect_uart(self):
    #     select_data = self.comboBox.currentData()
    #     if select_data is not None: 
    #         self.connect = serial.Serial(port="COM4",baudrate=select_data)
    #         time.sleep(2)
    #         data_to_send = {"type":"command","command": "CONNECT"}
    #         json_data = json.dumps(data_to_send)
    #         json_data += "\n"
    #         self.connect.write(json_data.encode('utf-8'))
    #         respone = self.connect.readline().decode().strip()
            
    #         if respone == "ESP32 Connected":
    #             msg = QtWidgets.QMessageBox()
    #             msg.setInformativeText('Kết Nối Thành Công')
    #             msg.exec()
    #         else:
    #             msg1 = QtWidgets.QMessageBox()
    #             msg1.setInformativeText("Kết Nối Thất Bại")
    #             msg1.exec()
                
    # def connect_wifi(self):
    #     select_data = self.comboBox.currentData()
    #     if select_data is not None:
    #         self.connectwifi = serial.Serial(port="COM4",baudrate=select_data)
    #         data_to_send = {"type":"command","command":"WIFI"}
    #         json_data = json.dumps(data_to_send)
    #         json_data += "\n"
    #         self.connectwifi.write(json_data.encode('utf-8'))
    #         respone = self.connectwifi.readline().decode().strip()
        
    #         if respone == "Connected to WiFi":
    #             msg = QtWidgets.QMessageBox()
    #             msg.setInformativeText('Kết Nối WIFI Thành Công')
    #             msg.exec()
    #         else:
    #             msg1 = QtWidgets.QMessageBox()
    #             msg1.setInformativeText("Kết Nối WIFI Thất Bại")
    #             msg1.exec()
    
    # def send_data(self):
    #     select_data = self.comboBox.currentData()
    #     if select_data is not None:
    #         self.send = serial.Serial(port="COM4",baudrate=select_data)
    #         time.sleep(2)
            
    #         x1_data = self.x1.text()
    #         y1_data = self.y1.text()
    #         z1_data = self.z1.text()
        
    #         x2_data = self.x2.text()
    #         y2_data = self.y2.text()
    #         z2_data = self.z2.text()
        
    #         x3_data = self.x3.text()
    #         y3_data = self.y3.text()
    #         z3_data = self.z3.text()
        
    #         x4_data = self.x4.text()
    #         y4_data = self.y4.text()
    #         z4_data = self.z4.text()
        
    #         x5_data = self.x5.text()
    #         y5_data = self.y5.text()
    #         z5_data = self.z5.text()
            
    #         data_to_send = {"type":"position",
    #                         "x1":x1_data,"y1":y1_data,"z1":z1_data,
    #                         "x2":x2_data,"y2":y2_data,"z2":z2_data,
    #                         "x3":x3_data,"y3":y3_data,"z3":z3_data,
    #                         "x4":x4_data,"y4":y4_data,"z4":z4_data,
    #                         "x5":x1_data,"y5":y5_data,"z5":z5_data}
            
    #         json_data_pos = json.dumps(data_to_send)
    #         json_data_pos += "\n"
            
    #         self.send.writelines(json_data_pos.encode('utf-8'))
            
    #         respone = self.send.readline().decode().strip()
            
    #         if respone == "done save pos":
    #             msg1 = QtWidgets.QMessageBox()
    #             msg1.setInformativeText("Đã lưu lệnh")
    #             msg1.exec()
            
    # def run_auto(self):
    #     select_data = self.comboBox.currentData()
    #     if select_data is not None:
    #         self.auto_2 =  serial.Serial(port="COM4",baudrate=select_data)
    #         time.sleep(2)
    #         data_to_send = {"type":"command","command":"autorun"}
    #         json_data = json.dumps(data_to_send)
    #         json_data += "\n"
            
    #         self.auto_2.write(json_data.encode('utf-8'))
    
    # def reset_pos(self):
    #     select_data = self.comboBox.currentData()
    #     if select_data is not None:
    #         self.reset = serial.Serial(port="COM4", baudrate=select_data)
    #         time.sleep(2)
    #         data_to_send = {"type":"command","command":"delete"}
    #         json_data = json.dumps(data_to_send)
    #         json_data += "\n"
    #         self.reset.write(json_data.encode('utf-8'))
            
    #         respone = self.reset.readline().decode().strip()
            
    #         if respone == "None data in Robot":
    #             mess1 = QtWidgets.QMessageBox()
    #             mess1.setInformativeText("Robot chưa có lệnh học!")
    #             mess1.exec()
    #         else :
    #             mess2 = QtWidgets.QMessageBox()
    #             mess2.setInformativeText("Đã xóa lệnh!")
    #             mess2.exec()

    # def set_home(self):
    #     select_data = self.comboBox.currentData()
    #     if select_data is not None:
    #         self.home = serial.Serial(port="COM4",baudrate=select_data)
    #         time.sleep(2)
    #         data_to_send = {"type":"command","command":"sethome"}
    #         json_data = json.dumps(data_to_send)
    #         json_data += "\n"
            
    #         self.home.write(json_data.encode('utf-8'))
            
    #         respone = self.home.readline().decode().strip()
            
    #         if respone == "home":
    #             mess1 = QtWidgets.QMessageBox()
    #             mess1.setInformativeText("set home thành công!")
    #             mess1.exec()
                
    #         else :
    #             mess2 = QtWidgets.QMessageBox()
    #             mess2.setInformativeText("set home thất bại!")
    #             mess2.exec()
    
       
            
if __name__ == "__main__":
    import sys
    import serial
    import time
    import matplotlib
    matplotlib.use('Agg')  # Cho backend không tương tác
    import matplotlib.pyplot as plt
    from PyQt6.QtCore import QThread,pyqtSignal
    from PyQt6.QtWidgets import QSlider
    import serial.tools
    import serial.tools.list_ports 
    import json 
    import kinematicRobot
    app = QtWidgets.QApplication(sys.argv)
    import matplotlib.pyplot as plt
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
